# Generated by Django 3.2.4 on 2021-06-20 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата создания справочника'),
        ),
        migrations.AlterField(
            model_name='directory',
            name='version',
            field=models.CharField(max_length=50, unique=True, verbose_name='Версия справочника'),
        ),
    ]
